apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-management
  template:
    metadata:
      labels:
        app: student-management
    spec:
      containers:
        - name: student-management
          image: psbd/student-management:1.0.11
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: student-management-service
spec:
  selector:
    app: student-management
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
